### ISSUE TITLE
Dynamically add rows to table - fix issue

### ISSUE THREAD

**Issue by ofirattia** [kaiocesar/codeigniter-angular#1]
Hi, if you want to add dynamically the rows to the table, you should give id to the table and then uncomment your line ( $scope.push... )

you can use

```
var scope = angular.element(document.getElementById("t")).scope();
scope.rows.push({name: $scope.name, city: $scope.city});
```

**Comment by kaiocesar** [comment]
Hey brother, thank you for help me, I have repaired whats was not working.
